#include "stdafx.h"
#include <cassert>
#include <iostream>
#include <string>
#include <vector>
#include <algorithm>
#include <sstream>
#include <ctime>
#include "tinyxml2.h"
#include "CommonUtil.h"
#include "PDFCreator.h"
#include "Trade.h"


using namespace std;

const char* pval = nullptr;
static std::string title = "";


//typedef struct TRADE_st
//{
//	int row;
//	int col;
//	int style;//0 default 1 red 2 bold 3 redbold
//	int colTotal;
//	std::string label;
//	std::string value;
//	int keyword;
//	TRADE_st()
//	{
//		row = 0;
//		col = 0;
//		colTotal = 0;
//		label = "";
//		value = "";
//		keyword = 0;
//	}
//}TRADE,*PTRADE;


std::vector<Trade> vec_trade;


//string data()
//{
//	return	"<?xml version=\"1.0\" encoding=\"utf-8\"?>"
//		"<PRT>"
//		"<Title>无纸化凭证</Title>"
//		"<PrtType>1</PrtType>"
//		"<Items>"
//		"<Item>"
//		"<Label>柜员流水号：</Label>"
//		"<Value>028884000000028</Label>"
//		"<RowNum>0</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>交易机构：</Label>"
//		"<Value>020501</Label>"
//		"<RowNum>1</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>交易日期：</Label>"
//		"<Value>2018/09/23</Label>"
//		"<RowNum>0</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>交易时间：</Label>"
//		"<Value>11:51:04</Label>"
//		"<RowNum>1</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>交易柜员：</Label>"
//		"<Value>028884信贷</Label>"
//		"<RowNum>0</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>授权柜员：</Label>"
//		"<Value />"
//		"<RowNum>1</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>核对信息</Label>"
//		"<Value>核对信息核对信息核对信息核对信息核对信息核对信息核对信息核对信息</Label>"
//		"<RowNum>3</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"<ColTotal>3</ColTotal>"
//		"</Item>"
//		"<Item>"
//		"<Label>客户姓名：</Label>"
//		"<Value>宝马一哥</Label>"
//		"<RowNum>4</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>1</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>手机号码：</Label>"
//		"<Value>19988856333</Label>"
//		"<RowNum>4</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>1</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>现转标志：</Label>"
//		"<Value>现金</Label>"
//		"<RowNum>4</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>金额（小写）：</Label>"
//		"<Value>15.00</Label>"
//		"<RowNum>5</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>大写：</Label>"
//		"<Value>壹拾伍元整</Label>"
//		"<RowNum>5</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>币种：</Label>"
//		"<Value>人民币</Label>"
//		"<RowNum>5</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>移动金融SD卡号码：</Label>"
//		"<Value>6412017000096滴滴答答的哒哒哒等到</Label>"
//		"<RowNum>6</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>3</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>【凭证注销信息】</Label>"
//		"<Value />"
//		"<RowNum>9</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"<ColTotal>4</ColTotal>"
//		"</Item>"
//		"<Item>"
//		"<Label>凭证序号</Label>"
//		"<Value></Label>"
//		"<RowNum>10</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>凭证号码</Label>"
//		"<Value></Label>"
//		"<RowNum>10</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>凭证状态</Label>"
//		"<Value></Label>"
//		"<RowNum>10</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>测试状态</Label>"
//		"<Value></Label>"
//		"<RowNum>10</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>1</Label>"
//		"<Value></Label>"
//		"<RowNum>11</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>1234567890</Label>"
//		"<Value></Label>"
//		"<RowNum>11</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>成功</Label>"
//		"<Value></Label>"
//		"<RowNum>11</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>成功</Label>"
//		"<Value></Label>"
//		"<RowNum>11</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2</Label>"
//		"<Value></Label>"
//		"<RowNum>12</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>1234567890</Label>"
//		"<Value></Label>"
//		"<RowNum>12</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>成功</Label>"
//		"<Value></Label>"
//		"<RowNum>12</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>成功</Label>"
//		"<Value></Label>"
//		"<RowNum>12</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>【销户解约信息】</Label>"
//		"<Value />"
//		"<RowNum>14</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"<ColTotal>7</ColTotal>"
//		"</Item>"
//		"<Item>"
//		"<Label>序号</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>签约类型</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>签约渠道</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>签约手机</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>签约机构</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>4</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>签约日期</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>5</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>解约日期</Label>"
//		"<Value></Label>"
//		"<RowNum>15</RowNum>"
//		"<ColNum>6</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>1</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>面签</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>手机银行</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>13333333333</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>012345</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>4</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2019-01-01</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>5</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2019-01-01</Label>"
//		"<Value></Label>"
//		"<RowNum>16</RowNum>"
//		"<ColNum>6</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>0</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>面签</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>1</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>手机银行</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>2</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>13333333333</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>3</ColNum>"
//		"<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>012345</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>4</ColNum>"
//		"<Style>3</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2019-01-01</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>5</ColNum>"
//		"<Style>2</Style>"
//		"</Item>"
//		"<Item>"
//		"<Label>2019-01-01</Label>"
//		"<Value></Label>"
//		"<RowNum>17</RowNum>"
//		"<ColNum>6</ColNum>"
//		"<Style>1</Style>"
//		"</Item>"
//		"</Items>"
//		"</PRT>";
//}

int ParseTrade(const std::string& trade, const std::string& param)
{
	//totalRows = 0;
	vec_trade.clear();
	vector<shared_ptr<Trade>> trades;
	//Transaction transaction;
	tinyxml2::XMLDocument xmlDoc;
	auto error = xmlDoc.Parse(trade.c_str(), trade.length());
	int maxRow = 0;

	std::string trade_Code = CommonUtil::parse_value(param, "Trade_Code_Cd");

	tinyxml2::XMLElement *root = xmlDoc.FirstChildElement("PRT");
	assert(root);
	tinyxml2::XMLElement *child1 = root->FirstChildElement("Title");
	pval = child1->GetText();
	if(pval)
	{
		title = trade_Code + " " + pval;
	}

	tinyxml2::XMLElement *child2 = root->FirstChildElement("Items");
	tinyxml2::XMLElement *child21 = child2->FirstChildElement("Item");

	while (child21)
	{
		Trade trade;

		pval = child21->FirstChildElement("RowNum")->GetText();
		if (pval){
			trade.row = atoi(pval);
			maxRow = atoi(pval);
		}
		pval = child21->FirstChildElement("ColNum")->GetText();
		if (pval){
			trade.col = atoi(pval);
		}
		pval = child21->FirstChildElement("Style")->GetText();
		if (pval){
			trade.style = atoi(pval);
		}
		if (child21->FirstChildElement("ColTotal"))
		{
			pval = child21->FirstChildElement("ColTotal")->GetText();
			if (pval){
				trade.colTotal = atoi(pval);
			}
		}
		pval = child21->FirstChildElement("Label")->GetText();
		if (pval){
			trade.label = pval;
		}
		pval = child21->FirstChildElement("Value")->GetText();
		if (pval){
			trade.value = pval;
		}
		if (child21->FirstChildElement("Keyword"))
		{
			pval = child21->FirstChildElement("Keyword")->GetText();
			if (pval){
				trade.keyword = atoi(pval);
			}
		}

		//if(child21->FirstChildElement("RowNum"))
		//trade.row = atoi(child21->FirstChildElement("RowNum")->GetText());
		//if(child21->FirstChildElement("ColNum"))
		//trade.col = atoi(child21->FirstChildElement("ColNum")->GetText());
		//if(child21->FirstChildElement("Style"))
		//trade.style = atoi(child21->FirstChildElement("Style")->GetText());
		//if(child21->FirstChildElement("ColTotal"))
		//trade.colTotal = atoi(child21->FirstChildElement("ColTotal")->GetText());
		//if(child21->FirstChildElement("Label"))
		//trade.label = child21->FirstChildElement("Label")->GetText();
		//if(child21->FirstChildElement("Value"))
		//trade.value = child21->FirstChildElement("Value")->GetText();

		vec_trade.push_back(trade);
		child21 = child21->NextSiblingElement();

	}

	if (vec_trade.size() > 0)
		std::sort(vec_trade.begin(), vec_trade.end(), [](const Trade& left, const Trade& right)->bool
	{
		if (left.row == right.row)
			return left.col < right.col;
		else
			return left.row < right.row;
	});

	//int i = 0;

	int colsnum = 3;
	vec_trade[0].colTotal = colsnum;
	for(size_t j=1;j< vec_trade.size();++j)
	{
		auto it = &vec_trade.at(j);
		if (it->col == 0)
		{
			if (it->colTotal > 0)
			{
				colsnum = it->colTotal;
				it->colTotal = 1;
			}
		}
		it->colTotal = colsnum;
	}
	//DataRow dataRow;
	//dataRow.maxRows = maxRow;
	//dataRow.trades = trades;
	return maxRow;
}

string now()
{
	SYSTEMTIME time;
	GetLocalTime(&time);
	stringstream ss;
	ss << time.wYear << "-"
		<< time.wMonth << "-"
		<< time.wDay << " "
		<< time.wHour << ":"
		<< time.wMinute << ":"
		<< time.wSecond;
	return ss.str();
}

string tradeNumber()
{
	stringstream ss;
	ss << time(NULL);
	return ss.str();
}

string param()
{
	return "Org_No=500101&Trade_Tellr_No=500126&Trade_Time="+now()+"&Teller_Serl_No="+tradeNumber()+"&Trade_Code_Cd=100003&Trade_Nm=个人存款业务&Info_Flag=1&File_Nm=test&Identfctn_No=123456789012345678&Cust_Nm=张三&Timeout=100";
}

static vector<shared_ptr<Trade>> convert(const vector<Trade>& input)
{
	vector<shared_ptr<Trade>> vec;
	for_each(input.begin(), input.end(), [&vec](const Trade& trade)
	{
		auto p = make_shared<Trade>(trade);
		vec.push_back(p);
	});
	return vec;
}

static string A4_3Pages()
{
	return  "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		"<PRT>"
		"<Title>无纸化凭证</Title>"
		"<PrtType>1</PrtType>"
		"<Items>"
		"<Item>"
		"<Label>柜员流水号：</Label>"
		"<Value>028884000000028</Label>"
		"<RowNum>0</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>交易机构：</Label>"
		"<Value>020501</Label>"
		"<RowNum>1</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>交易日期：</Label>"
		"<Value>2018/09/23</Label>"
		"<RowNum>0</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>交易时间：</Label>"
		"<Value>11:51:04</Label>"
		"<RowNum>1</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>交易柜员：</Label>"
		"<Value>028884信贷</Label>"
		"<RowNum>0</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>授权柜员：</Label>"
		"<Value/>"
		"<RowNum>1</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>核对信息</Label>"
		"<Value>核对信息核对信息核对信息核对信息核对信息核对信息核对信息核对信息</Label>"
		"<RowNum>3</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>1</Style>"
		"<ColTotal>3</ColTotal>"
		"</Item>"
		"<Item>"
		"<Label>客户姓名：</Label>"
		"<Value>宝马一哥</Label>"
		"<RowNum>4</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>1</Style>"
		"</Item>"
		"<Item>"
		"<Label>手机号码：</Label>"
		"<Value>19988856333</Label>"
		"<RowNum>4</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>1</Style>"
		"</Item>"
		"<Item>"
		"<Label>现转标志：</Label>"
		"<Value>现金</Label>"
		"<RowNum>4</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>金额（小写）：</Label>"
		"<Value>15.00</Label>"
		"<RowNum>5</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>大写：</Label>"
		"<Value>壹拾伍元整</Label>"
		"<RowNum>5</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>币种：</Label>"
		"<Value>人民币</Label>"
		"<RowNum>5</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>移动金融SD卡号码：</Label>"
		"<Value>6412017000096滴滴答答的哒哒哒等到</Label>"
		"<RowNum>6</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>3</Style>"
		"</Item>"
		"<Item>"
		"<Label>【凭证注销信息】</Label>"
		"<Value/>"
		"<RowNum>9</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"<ColTotal>4</ColTotal>"
		"</Item>"
		"<Item>"
		"<Label>凭证序号</Label>"
		"<Value/>"
		"<RowNum>10</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>凭证号码</Label>"
		"<Value/>"
		"<RowNum>10</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>凭证状态</Label>"
		"<Value/>"
		"<RowNum>10</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>测试状态</Label>"
		"<Value/>"
		"<RowNum>10</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>1</Label>"
		"<Value/>"
		"<RowNum>11</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>1234567890</Label>"
		"<Value/>"
		"<RowNum>11</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>成功</Label>"
		"<Value/>"
		"<RowNum>11</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>成功</Label>"
		"<Value/>"
		"<RowNum>11</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>2</Label>"
		"<Value/>"
		"<RowNum>12</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>1234567890</Label>"
		"<Value/>"
		"<RowNum>12</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>成功</Label>"
		"<Value/>"
		"<RowNum>12</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>成功</Label>"
		"<Value/>"
		"<RowNum>12</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>【销户解约信息】</Label>"
		"<Value/>"
		"<RowNum>14</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"<ColTotal>7</ColTotal>"
		"</Item>"
		"<Item>"
		"<Label>序号</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>签约类型</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>签约渠道</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>签约手机</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>签约机构</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>4</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>签约日期</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>5</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>解约日期</Label>"
		"<Value/>"
		"<RowNum>15</RowNum>"
		"<ColNum>6</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>1</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>面签</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>手机银行</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>13333333333</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>012345</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>4</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>2019-01-01</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>5</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>2019-01-01</Label>"
		"<Value/>"
		"<RowNum>16</RowNum>"
		"<ColNum>6</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>2</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>面签</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>1</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>手机银行</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>2</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>11111111111111111111113333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒1111111111111111111111111</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>3</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>012345</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>4</ColNum>"
		"<Style>3</Style>"
		"</Item>"
		"<Item>"
		"<Label>2019-01-01</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>5</ColNum>"
		"<Style>2</Style>"
		"</Item>"
		"<Item>"
		"<Label>2019-01-01</Label>"
		"<Value/>"
		"<RowNum>17</RowNum>"
		"<ColNum>6</ColNum>"
		"<Style>1</Style>"
		"</Item>"
		"<Item>"
		"<Label>备注：</Label>"
		"<Value/>"
		"<RowNum>34</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"<Value/>"
		"<RowNum>35</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>备注：</Label>"
		"<Value/>"
		"<RowNum>54</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"<Value/>"
		"<RowNum>55</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>备注：</Label>"
		"<Value/>"
		"<RowNum>94</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"<Item>"
		"<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"<Value/>"
		"<RowNum>95</RowNum>"
		"<ColNum>0</ColNum>"
		"<Style>0</Style>"
		"</Item>"
		"</Items>"
		"</PRT>";

}

string applicationPath()
{
	vector<char> buffer(MAX_PATH);
	GetModuleFileNameA(NULL, &buffer[0], MAX_PATH);
	string path(&buffer[0]);
	auto index = path.rfind('\\');
	return path.substr(0, index + 1);
}

string overLongData()
{
	return "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		"<PRT>"
		"	<Title>无纸化凭证</Title>"
		"	<PrtType>1</PrtType>"
		"	<Items>"
		"		<Item>"
		"			<Label>【销户解约信息】</Label>"
		"			<Value/>"
		"			<RowNum>14</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"			<ColTotal>7</ColTotal>"
		"		</Item>"
		"		<Item>"
		"			<Label>序号</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约类型</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约渠道</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约手机</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约机构</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约日期</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>解约日期</Label>"
		"			<Value/>"
		"			<RowNum>15</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>1</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>面签</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>手机银行</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>13333333333</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>012345</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>16</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>面签</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>手机银行</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>11111111111111111111113333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒3333333333s滴滴答答的哒哒哒1111111111111111111111111</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>012345</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>3</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>2</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>17</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>1</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>备注：</Label>"
		"			<Value/>"
		"			<RowNum>34</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"			<Value/>"
		"			<RowNum>35</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>备注：</Label>"
		"			<Value/>"
		"			<RowNum>54</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"			<Value/>"
		"			<RowNum>55</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>备注：</Label>"
		"			<Value/>"
		"			<RowNum>94</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>本人已核对上述交易信息,并确认与本人申请办理的业务内容一致</Label>"
		"			<Value/>"
		"			<RowNum>95</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"	</Items>"
		"</PRT>";

}

//string data()
//{
//	return "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
//		"<PRT>"
//		"  <Title>现金尾箱限额管理</Title>"
//		"  <PrtType>1</PrtType>"
//		"  <Items>"
//		"    <Item>"
//		"      <Label>柜员流水号：</Label>"
//		"      <Value>123456789</Value>"
//		"      <RowNum>0</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>交易日期：</Label>"
//		"      <Value>2019/06/27</Value>"
//		"      <RowNum>0</RowNum>"
//		"      <ColNum>1</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>交易柜员：</Label>"
//		"      <Value>381025冉建</Value>"
//		"      <RowNum>0</RowNum>"
//		"      <ColNum>2</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>交易机构：</Label>"
//		"      <Value>382001 111111111111111111111111111111111111111111111111111111</Value>"
//		"      <RowNum>1</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		//"    <Item>"
//		//"      <Label>交易时间：</Label>"
//		//"      <Value>18:12:27</Value>"
//		//"      <RowNum>1</RowNum>"
//		//"      <ColNum>1</ColNum>"
//		//"      <Style>0</Style>"
//		//"    </Item>"
//		"    <Item>"
//		"      <Label>授权柜员：</Label>"
//		"      <Value>1111111111111111111111111111111111111111111111111111111111111111111</Value>"
//		"      <RowNum>1</RowNum>"
//		"      <ColNum>2</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Value/>"
//		"      <RowNum>3</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"      <Label>【交易信息】</Label>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>操作标志：</Label>"
//		"      <Value>0-新增</Value>"
//		"      <RowNum>4</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>尾箱类别：</Label>"
//		"      <Value>0-柜员尾箱</Value>"
//		"      <RowNum>4</RowNum>"
//		"      <ColNum>1</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>币种：</Label>"
//		"      <Value>01-人民币</Value>"
//		"      <RowNum>4</RowNum>"
//		"      <ColNum>2</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>序号 员工号 柜员号 机构号 控制标志 限额</Label>"
//		"      <Value/>"
//		"      <RowNum>5</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>1 3437834 534535 543453 0-提示 10.00</Label>"
//		"      <Value/>"
//		"      <RowNum>6</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>2 2333333 555555 888888 1-限制办理业务 30.00</Label>"
//		"      <Value/>"
//		"      <RowNum>7</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>3 6666666 777777 333333 2-不控制 0.00 啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊</Label>"
//		"      <Value/>"
//		"      <RowNum>8</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>4 8888888 999999 777777 1-限制办理业务 20.00</Label>"
//		"      <Value/>"
//		"      <RowNum>9</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"    <Item>"
//		"      <Label>5 1111111 133333 777777 2-不控制 0.00</Label>"
//		"      <Value/>"
//		"      <RowNum>20</RowNum>"
//		"      <ColNum>0</ColNum>"
//		"      <Style>0</Style>"
//		"    </Item>"
//		"<Item>"
//		"	<Label>税收居民国地区1:</Label>"
//		"	<Value>ABW-阿鲁巴</Value>"
//		"	<RowNum>14</RowNum>"
//		"	<ColNum>0</ColNum>"
//		"	<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"	<Label>纳税人识别号</Label>"
//		"	<Value></Value>"
//		"	<RowNum>14</RowNum>"
//		"	<ColNum>1</ColNum>"
//		"	<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"	<Label>原因1：</Label>"
//		"	<Value>0-居民国地区不发放纳税人识别号</Value>"
//		"	<RowNum>15</RowNum>"
//		"	<ColNum>0</ColNum>"
//		"	<Style>0</Style>"
//		"</Item>"
//		"<Item>"
//		"	<Label>备注1:</Label>"
//		"	<Value></Value>"
//		"	<RowNum>15</RowNum>"
//		"	<ColNum>1</ColNum>"
//		"	<Style>0</Style>"
//		"</Item>"
//"<Item>"
//"	<Label>机构涉税状态原因备注:</Label>"
//"	<Value></Value>"
//"	<RowNum>13</RowNum>"
//"	<ColNum>0</ColNum>"
//"	<Style>0</Style>"
//"</Item>"


//		"  </Items>"
//		"</PRT>";
//}

//string data()
//{
//	return "<?xml version=\"1.0\" encoding=\"GBK\"?>"
//		"<PRT>"
//		"	<Title>非居民涉税信息查询维护</Title>"
//		"	<PrtType>1</PrtType>"
//		"	<Items>"
//		"		<Item>"
//		"			<Label>柜员流水号：</Label>"
//		"			<Value>043245000000017</Value>"
//		"			<RowNum>0</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>交易日期：</Label>"
//		"			<Value>2019/07/15</Value>"
//		"			<RowNum>0</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>交易柜员：</Label>"
//		"			<Value>043245李浩</Value>"
//		"			<RowNum>0</RowNum>"
//		"			<ColNum>2</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>交易机构：</Label>"
//		"			<Value>040401</Value>"
//		"			<RowNum>1</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>交易时间：</Label>"
//		"			<Value>16:59:48</Value>"
//		"			<RowNum>1</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>授权柜员：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>1</RowNum>"
//		"			<ColNum>2</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Value></Value>"
//		"			<RowNum>3</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"			<Label>【交易信息】</Label>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构地址（英文或拼音）：</Label>"
//		"			<Value>zzzz</Value>"
//		"			<RowNum>10</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构地址（中文）：</Label>"
//		"			<Value>是大方的说法</Value>"
//		"			<RowNum>11</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构涉税信息采集渠道：</Label>"
//		"			<Value>01-柜面</Value>"
//		"			<RowNum>12</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构涉税标识状态原因备注：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>13</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>税收居民国地区1：</Label>"
//		"			<Value>ABW-阿鲁巴</Value>"
//		"			<RowNum>14</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>纳税人识别号1：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>14</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>原因1：</Label>"
//		"			<Value>0-居民国（地区）不发放纳税人识别号</Value>"
//		"			<RowNum>15</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>备注1：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>15</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>税收居民国地区2：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>16</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>纳税人识别号2：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>16</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>原因2：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>17</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>备注2：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>17</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>税收居民国地区3：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>18</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>纳税人识别号3：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>18</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>原因3：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>19</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>备注3：</Label>"
//		"			<Value></Value>"
//		"			<RowNum>19</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>客户号：</Label>"
//		"			<Value>2720567318</Value>"
//		"			<RowNum>4</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>客户类型：</Label>"
//		"			<Value>1-对公客户</Value>"
//		"			<RowNum>4</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>客户全称：</Label>"
//		"			<Value>美的美的</Value>"
//		"			<RowNum>5</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>客户非中文名称：</Label>"
//		"			<Value>zzzz</Value>"
//		"			<RowNum>6</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构类别：</Label>"
//		"			<Value>2-其他非金融机构</Value>"
//		"			<RowNum>6</RowNum>"
//		"			<ColNum>1</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>国别地区：</Label>"
//		"			<Value>156-中国</Value>"
//		"			<RowNum>7</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构税收居民身份类型：</Label>"
//		"			<Value>2-仅为非居民</Value>"
//		"			<RowNum>8</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"		<Item>"
//		"			<Label>机构涉税标识状态：</Label>"
//		"			<Value>0-已声明</Value>"
//		"			<RowNum>9</RowNum>"
//		"			<ColNum>0</ColNum>"
//		"			<Style>0</Style>"
//		"		</Item>"
//		"	</Items>"
//		"</PRT>";
//}

string data()
{
	return "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
		"<PRT>"
		"	<Title>无纸化凭证</Title>"
		"	<PrtType>1</PrtType>"
		"	<Items>"
		"		<Item>"
		"			<Label>柜员流水号：</Label>"
		"			<Value>028884000000028</Value>"
		"			<RowNum>0</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>交易机构：</Label>"
		"			<Value>020501</Value>"
		"			<RowNum>1</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>交易日期：</Label>"
		"			<Value>2018/09/23</Value>"
		"			<RowNum>0</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>交易时间：</Label>"
		"			<Value>11:51:04</Value>"
		"			<RowNum>1</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>交易柜员：</Label>"
		"			<Value>028884信贷</Value>"
		"			<RowNum>0</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>授权柜员：</Label>"
		"			<Value/>"
		"			<RowNum>1</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>核对信息</Label>"
		"			<Value>核对信息核对信息核对信息核对信息核对信息核对信息核对信息核对信息</Value>"
		"			<RowNum>3</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>1</Style>"
		"			<ColTotal>3</ColTotal>"
		"		</Item>"
		"		<Item>"
		"			<Label>客户姓名：</Label>"
		"			<Value>宝马一哥</Value>"
		"			<RowNum>4</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>1</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>手机号码：</Label>"
		"			<Value>19988856333</Value>"
		"			<RowNum>4</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>1</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>现转标志：</Label>"
		"			<Value>现金</Value>"
		"			<RowNum>4</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>金额（小写）：</Label>"
		"			<Value>40.00</Value>"
		"			<RowNum>5</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>大写：</Label>"
		"			<Value>壹拾伍元整</Value>"
		"			<RowNum>5</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>币种：</Label>"
		"			<Value>人民币</Value>"
		"			<RowNum>5</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>移动金融SD卡号码：</Label>"
		"			<Value>6412042000096滴滴答答的哒哒哒等到</Value>"
		"			<RowNum>6</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>3</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>【凭证注销信息】</Label>"
		"			<Value/>"
		"			<RowNum>9</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"			<ColTotal>4</ColTotal>"
		"		</Item>"
		"		<Item>"
		"			<Label>凭证序号</Label>"
		"			<Value/>"
		"			<RowNum>10</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>凭证号码</Label>"
		"			<Value/>"
		"			<RowNum>10</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>凭证状态</Label>"
		"			<Value/>"
		"			<RowNum>10</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>测试状态</Label>"
		"			<Value/>"
		"			<RowNum>10</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>1</Label>"
		"			<Value/>"
		"			<RowNum>11</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>1234567890</Label>"
		"			<Value/>"
		"			<RowNum>11</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>成功</Label>"
		"			<Value/>"
		"			<RowNum>11</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>成功</Label>"
		"			<Value/>"
		"			<RowNum>11</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2</Label>"
		"			<Value/>"
		"			<RowNum>12</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>1234567890</Label>"
		"			<Value/>"
		"			<RowNum>12</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>成功</Label>"
		"			<Value/>"
		"			<RowNum>12</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>成功</Label>"
		"			<Value/>"
		"			<RowNum>12</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>【销户解约信息】</Label>"
		"			<Value/>"
		"			<RowNum>14</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"			<ColTotal>7</ColTotal>"
		"		</Item>"
		"		<Item>"
		"			<Label>序号</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约类型</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约渠道</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约手机</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约机构</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>签约日期</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>解约日期</Label>"
		"			<Value/>"
		"			<RowNum>39</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>0</Style>"
		"			<Keyword>0</Keyword>"
		"		</Item>"
		"		<Item>"
		"			<Label>1</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>面签</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>手机银行</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>13333333333</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>012345</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>40</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>0</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>面签</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>1</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>手机银行</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>2</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>13333333333s滴滴答答的哒哒哒</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>3</ColNum>"
		"			<Style>0</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>012345</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>4</ColNum>"
		"			<Style>3</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>5</ColNum>"
		"			<Style>2</Style>"
		"		</Item>"
		"		<Item>"
		"			<Label>2019-01-01</Label>"
		"			<Value/>"
		"			<RowNum>41</RowNum>"
		"			<ColNum>6</ColNum>"
		"			<Style>1</Style>"
		"		</Item>"
		"	</Items>"
		"</PRT>";
}



int main(int, char**)
{
	ParseTrade(data(), param());
	PDFCreator creator;
	creator.setHorizonalMargin(10.0f);
	creator.setVerticalMargin(10.0f);
	creator.setLogoHeight(50.0f);
	creator.setLogoPath(applicationPath() + "\\logo\\logo.jpg");
	creator.setRowHeight(18.0f);
	creator.setTitleHeight(20.0);
	creator.setTitle(title);
	auto doc = creator.generateDocument(convert(vec_trade));
	auto fileName = applicationPath() + "temp.pdf";
	doc.saveToFile(fileName);
	doc.destroy();
	ShellExecuteA(NULL, "open", fileName.c_str(), NULL, NULL, SW_SHOW);
	cout << "Hello world" << endl;
	cin.get();
	return 0;
}
